let shopItemsData = [
  {
    id: "jfhgbvnscs",
    name: "Chocolate-Passion Delight",
    price: 10,
    desc: "A sumptuous layered entremet combining rich dark chocolate, passion fruit mousse, and fresh fruits, all topped with an irresistible glossy glaze.",
    img: "images/Patisserie6.jpeg",
  },
  {
    id: "ioytrhndcv",
    name: "Gourmet Escape",
    price: 21,
    desc: "A dream dessert combining cocoa sponge, vanilla mousse, and smooth caramel, adorned with red berries and a mirror glaze.",
    img: "images/Patisserie2.jpeg",
  },
  {
    id: "wuefbncxbsn",
    name: "Caramel and Vanilla Bliss",
    price: 25,
    desc: "A revisited classic with generous layers of vanilla cream — a true delight. ",
    img: "images/Patisserie8.jpeg",
  },
  {
    id: "thyfhcbcv",
    name: "Fruity Serenade",
    price: 30,
    desc: "A colorful and refreshing dessert with a fruity center, surrounded by a light sponge and a vibrant fruity glaze.",
    img: "images/Patisserie4.jpeg",
  },
  {
    id: "thyfhcbcw",
    name: "Festive Heart Cookies",
    price: 40,
    desc: "An assortment of heart-shaped shortbread cookies, decorated with colored sugar and pink or white icing — perfect for gifting or sharing.",
    img: "images/Patisserie5.jpeg",
  },
  {
    id: "thyfhcbci",
    name: "Coconut-Chocolate Mont Blanc",
    price: 27,
    desc: "Moist dark chocolate cake, coconut mousse, topped with a glossy mirror glaze.",
    img: "images/Patisserie1.jpeg",
  },
  {
    id: "thyfhcbch",
    name: "Mille-Feuille Crepe",
    price: 15,
    desc: "Spiraled rolled crepe with layers of vanilla and chocolate custard cream.",
    img: "images/Patisserie7.jpeg",
  },
  {
    id: "thyfhcbca",
    name: "Exotic Mango-Passion Cake",
    price: 33,
    desc: "Vanilla sponge cake, mango mousse, passion fruit core, and colorful fruity decoration.",
    img: "images/Patisserie3.jpeg",
  },
];
